use Medical_Schedule
go
-- Insert sample data into Admin table
INSERT INTO Admin (Username, Password) VALUES
('admin1', 'adminpassword1'),
('admin2', 'adminpassword2');

-- Insert sample data into Khoa table
INSERT INTO Khoa (TenKhoa, MoTa)
VALUES 
(N'Khoa Nội Tim mạch', N'Khoa Nội Tim mạch của chúng tôi chuyên sâu về các bệnh lý tim mạch nội khoa, bao gồm các vấn đề như suy tim, cao huyết áp, bệnh mạch vành, và các rối loạn nhịp tim. Với đội ngũ bác sĩ chuyên gia giàu kinh nghiệm, chúng tôi cung cấp dịch vụ khám, chẩn đoán và điều trị các bệnh lý tim mạch bằng các phương pháp tiên tiến nhất. Bệnh nhân sẽ được theo dõi và chăm sóc toàn diện, đảm bảo hiệu quả điều trị và cải thiện chất lượng cuộc sống. Chúng tôi còn tổ chức các chương trình tư vấn và giáo dục sức khỏe để giúp bệnh nhân và người nhà hiểu rõ hơn về bệnh lý và cách phòng ngừa. Khoa Nội Tim mạch cũng hợp tác chặt chẽ với các khoa khác trong bệnh viện để đưa ra phác đồ điều trị tổng thể, cá nhân hóa cho từng bệnh nhân, nhằm tối ưu hóa kết quả điều trị.'),
(N'Khoa Ngoại Tim mạch', N'Khoa Ngoại Tim mạch chuyên về phẫu thuật tim mạch, thực hiện các ca phẫu thuật từ đơn giản đến phức tạp như bắc cầu động mạch vành, thay van tim, và sửa chữa các dị tật tim bẩm sinh. Chúng tôi sử dụng các kỹ thuật phẫu thuật tiên tiến và công nghệ hiện đại để đảm bảo an toàn và hiệu quả cho bệnh nhân. Đội ngũ phẫu thuật viên của chúng tôi đều là những chuyên gia hàng đầu trong lĩnh vực này, cam kết mang lại kết quả tốt nhất cho bệnh nhân. Ngoài ra, khoa còn chú trọng đến việc chăm sóc hậu phẫu, hỗ trợ bệnh nhân phục hồi nhanh chóng và giảm thiểu biến chứng. Chúng tôi cũng cung cấp dịch vụ tư vấn trước phẫu thuật để bệnh nhân và gia đình hiểu rõ quy trình, rủi ro và lợi ích của phẫu thuật, từ đó đưa ra quyết định thông minh và an tâm khi điều trị.'),
(N'Khoa Cấp cứu', N'Khoa Cấp cứu của chúng tôi luôn sẵn sàng 24/7 để tiếp nhận và xử lý các trường hợp cấp cứu tim mạch. Với trang thiết bị hiện đại và đội ngũ y bác sĩ có chuyên môn cao, chúng tôi đảm bảo cung cấp dịch vụ cấp cứu kịp thời và hiệu quả. Các trường hợp cấp cứu như nhồi máu cơ tim, đột quỵ và các rối loạn nhịp tim nguy hiểm được xử lý nhanh chóng để giảm thiểu nguy cơ và tăng cơ hội sống sót cho bệnh nhân. Khoa Cấp cứu còn phối hợp chặt chẽ với các khoa khác trong bệnh viện để đảm bảo bệnh nhân được chăm sóc liên tục và toàn diện, từ giai đoạn cấp cứu đến khi ổn định và phục hồi. Chúng tôi cũng thường xuyên tham gia các khóa đào tạo và diễn tập cấp cứu để nâng cao kỹ năng và sẵn sàng ứng phó với mọi tình huống khẩn cấp.'),
(N'Khoa Nhi', N'Khoa Nhi chuyên về các bệnh tim mạch ở trẻ em, từ sơ sinh đến thanh thiếu niên. Chúng tôi cung cấp dịch vụ khám, chẩn đoán và điều trị các bệnh lý tim mạch bẩm sinh và mắc phải ở trẻ em. Với đội ngũ bác sĩ nhi khoa giàu kinh nghiệm và trang thiết bị hiện đại, chúng tôi cam kết mang lại sự chăm sóc tốt nhất cho các bệnh nhân nhỏ tuổi. Khoa Nhi cũng chú trọng đến việc hỗ trợ tâm lý cho trẻ em và gia đình, giúp các em vượt qua quá trình điều trị một cách dễ dàng và thoải mái. Chúng tôi còn tổ chức các hoạt động giáo dục và vui chơi cho trẻ em trong thời gian nằm viện, tạo môi trường thân thiện và ấm áp. Bên cạnh đó, khoa cũng hợp tác với các tổ chức y tế quốc tế để cập nhật và áp dụng những tiến bộ y học mới nhất vào công tác điều trị.'),
(N'Khoa Hồi sức tích cực', N'Khoa Hồi sức tích cực chuyên chăm sóc các bệnh nhân nặng cần hỗ trợ hô hấp và tuần hoàn. Với đội ngũ bác sĩ và điều dưỡng viên chuyên nghiệp, chúng tôi cung cấp dịch vụ chăm sóc đặc biệt cho các bệnh nhân sau phẫu thuật tim, suy tim cấp và các tình trạng nguy kịch khác. Trang thiết bị hiện đại và các biện pháp điều trị tiên tiến giúp chúng tôi đảm bảo an toàn và hiệu quả cao nhất cho bệnh nhân. Chúng tôi cũng chú trọng đến việc theo dõi sát sao và điều chỉnh phác đồ điều trị kịp thời dựa trên tình trạng cụ thể của từng bệnh nhân. Ngoài ra, khoa còn hỗ trợ tư vấn và huấn luyện cho gia đình bệnh nhân về cách chăm sóc và theo dõi tình trạng sức khỏe sau khi xuất viện.'),
(N'Khoa Chẩn đoán hình ảnh', N'Khoa Chẩn đoán hình ảnh chuyên thực hiện các kỹ thuật hình ảnh y học như siêu âm, X-quang, CT scan và MRI để chẩn đoán các bệnh lý tim mạch. Với trang thiết bị tiên tiến và đội ngũ kỹ thuật viên giàu kinh nghiệm, chúng tôi cung cấp hình ảnh chất lượng cao và chính xác, hỗ trợ đắc lực cho công tác chẩn đoán và điều trị. Khoa Chẩn đoán hình ảnh luôn cập nhật các công nghệ mới nhất và áp dụng vào thực tiễn, đảm bảo mang lại kết quả tốt nhất cho bệnh nhân. Chúng tôi cũng hợp tác chặt chẽ với các khoa lâm sàng để đưa ra chẩn đoán chính xác và nhanh chóng, giúp bệnh nhân được điều trị kịp thời và hiệu quả.'),
(N'Khoa Sinh hóa', N'Khoa Sinh hóa chuyên phân tích và xét nghiệm sinh hóa để chẩn đoán và theo dõi các bệnh lý tim mạch. Với hệ thống phòng thí nghiệm hiện đại và đội ngũ chuyên viên kỹ thuật giàu kinh nghiệm, chúng tôi cung cấp các kết quả xét nghiệm chính xác và nhanh chóng. Các xét nghiệm sinh hóa giúp phát hiện sớm các rối loạn tim mạch, đánh giá hiệu quả điều trị và theo dõi tiến triển của bệnh. Khoa Sinh hóa cũng chú trọng đến việc kiểm soát chất lượng và tuân thủ các quy trình tiêu chuẩn quốc tế, đảm bảo độ tin cậy cao của các kết quả xét nghiệm. Chúng tôi còn cung cấp dịch vụ tư vấn và giải thích kết quả xét nghiệm cho bệnh nhân và bác sĩ, hỗ trợ đưa ra các quyết định điều trị hợp lý.'),
(N'Khoa Dinh dưỡng', N'Khoa Dinh dưỡng chuyên tư vấn và điều trị dinh dưỡng cho bệnh nhân tim mạch. Chúng tôi cung cấp các chương trình dinh dưỡng cá nhân hóa dựa trên tình trạng sức khỏe và nhu cầu cụ thể của từng bệnh nhân. Các chuyên gia dinh dưỡng của chúng tôi sẽ hướng dẫn bệnh nhân cách lựa chọn thực phẩm và xây dựng chế độ ăn uống lành mạnh, hỗ trợ quá trình điều trị và phòng ngừa bệnh tim mạch. Khoa Dinh dưỡng còn tổ chức các buổi tư vấn và hội thảo về dinh dưỡng, giúp bệnh nhân và cộng đồng nâng cao nhận thức về vai trò của dinh dưỡng trong chăm sóc sức khỏe tim mạch. Chúng tôi cũng hợp tác với các khoa khác trong bệnh viện để đưa ra các phác đồ dinh dưỡng toàn diện, hỗ trợ tối ưu cho quá trình điều trị và phục hồi của bệnh nhân.'),
(N'Khoa Phục hồi chức năng', N'Khoa Phục hồi chức năng chuyên cung cấp các dịch vụ phục hồi chức năng cho bệnh nhân sau phẫu thuật và điều trị tim mạch. Với đội ngũ chuyên gia vật lý trị liệu và trang thiết bị hiện đại, chúng tôi thiết kế các chương trình phục hồi cá nhân hóa giúp bệnh nhân nhanh chóng phục hồi chức năng và cải thiện chất lượng cuộc sống. Các dịch vụ phục hồi chức năng bao gồm tập luyện thể dục, xoa bóp trị liệu, và các biện pháp hỗ trợ khác. Khoa Phục hồi chức năng cũng chú trọng đến việc theo dõi tiến trình phục hồi của bệnh nhân và điều chỉnh phác đồ điều trị kịp thời để đạt hiệu quả tốt nhất. Chúng tôi còn cung cấp các chương trình giáo dục và tư vấn cho bệnh nhân và gia đình về cách duy trì sức khỏe và phòng ngừa tái phát bệnh.'),
(N'Khoa Tim mạch can thiệp', N'Khoa Tim mạch can thiệp chuyên thực hiện các can thiệp tim mạch không phẫu thuật như đặt stent, nong mạch và bít lỗ thông liên nhĩ. Với đội ngũ bác sĩ can thiệp giàu kinh nghiệm và trang thiết bị hiện đại, chúng tôi cung cấp các dịch vụ can thiệp an toàn và hiệu quả, giúp bệnh nhân phục hồi nhanh chóng mà không cần phải trải qua phẫu thuật mở ngực. Khoa Tim mạch can thiệp còn hợp tác chặt chẽ với các khoa lâm sàng khác để đưa ra các phác đồ điều trị toàn diện và cá nhân hóa cho từng bệnh nhân. Chúng tôi cũng chú trọng đến việc tư vấn và hướng dẫn bệnh nhân về các biện pháp phòng ngừa và chăm sóc sau can thiệp, giúp duy trì kết quả điều trị lâu dài và ngăn ngừa biến chứng.');


-- Insert sample data into BacSi table
INSERT INTO BacSi (hoten, [password], namSinh, SDT, gioiTinh, email, HocVan, Sonamcongtac, MoTa)
VALUES
(N'Nguyễn Văn A', 'password1', 1980, '0123456789', 0, 'nguyenvana@example.com', N'Tiến sĩ Tim mạch', 10, N'Bác sĩ Nguyễn Văn A là một chuyên gia Tim mạch với bằng Tiến sĩ và hơn 10 năm kinh nghiệm trong lĩnh vực này. Ông đã tham gia nhiều dự án nghiên cứu quan trọng và có nhiều bài báo khoa học được công bố trên các tạp chí y học uy tín. Ông chuyên về chẩn đoán và điều trị các bệnh lý tim mạch phức tạp như bệnh động mạch vành, suy tim và loạn nhịp tim. Ngoài ra, bác sĩ Nguyễn Văn A còn là giảng viên của một trường đại học y khoa danh tiếng, nơi ông truyền đạt kiến thức và kinh nghiệm của mình cho các thế hệ bác sĩ tương lai. Ông luôn cập nhật các phương pháp điều trị mới nhất và áp dụng chúng vào thực tế để mang lại kết quả tốt nhất cho bệnh nhân.'),
(N'Trần Thị B', 'password2', 1985, '0987654321', 1, 'tranthib@example.com', N'Thạc sĩ Nhi khoa', 8, N'Bác sĩ Trần Thị B là một chuyên gia Nhi khoa với bằng Thạc sĩ và 8 năm kinh nghiệm. Bà đã làm việc tại nhiều bệnh viện lớn và có kinh nghiệm phong phú trong việc chăm sóc và điều trị các bệnh nhi. Bà đặc biệt chú trọng đến việc theo dõi và quản lý sức khỏe của trẻ từ khi còn trong bụng mẹ đến khi trưởng thành. Bác sĩ Trần Thị B luôn tận tâm với nghề, không ngừng học hỏi và áp dụng các phương pháp điều trị tiên tiến nhất để mang lại sức khỏe tốt nhất cho trẻ em. Bà cũng thường xuyên tham gia các hội thảo quốc tế và các khóa đào tạo chuyên sâu để nâng cao kiến thức và kỹ năng.'),
(N'Phạm Văn C', 'password3', 1978, '0912345678', 0, 'phamvanc@example.com', N'Tiến sĩ Phẫu thuật tim mạch', 15, N'Bác sĩ Phạm Văn C là một chuyên gia Phẫu thuật tim mạch với hơn 15 năm kinh nghiệm. Ông đã thực hiện hàng ngàn ca phẫu thuật thành công, đặc biệt là các ca phẫu thuật phức tạp như phẫu thuật bắc cầu động mạch vành và thay van tim. Bác sĩ Phạm Văn C được đánh giá cao về kỹ năng phẫu thuật tinh vi và khả năng xử lý các tình huống khẩn cấp. Ông cũng là thành viên của nhiều hiệp hội phẫu thuật tim mạch quốc tế và thường xuyên tham gia các hội nghị chuyên ngành để cập nhật các kỹ thuật mới nhất trong lĩnh vực phẫu thuật tim mạch. Ông luôn đặt lợi ích của bệnh nhân lên hàng đầu và không ngừng nỗ lực để cải thiện chất lượng cuộc sống của họ.'),
(N'Lê Thị D', 'password4', 1990, '0934567890', 1, 'lethid@example.com', N'Thạc sĩ Nội khoa', 7, N'Bác sĩ Lê Thị D là một chuyên gia Nội khoa với bằng Thạc sĩ và 7 năm kinh nghiệm. Bà chuyên về chẩn đoán và điều trị các bệnh lý nội khoa như tiểu đường, cao huyết áp, bệnh thận và các bệnh lý tiêu hóa. Bác sĩ Lê Thị D luôn chú trọng đến việc cung cấp dịch vụ chăm sóc toàn diện và cá nhân hóa cho từng bệnh nhân. Bà tin rằng việc lắng nghe và hiểu rõ nhu cầu của bệnh nhân là yếu tố quan trọng để đưa ra các giải pháp điều trị hiệu quả. Bà cũng thường xuyên tham gia các khóa đào tạo và hội thảo y khoa để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Hoàng Văn E', 'password5', 1982, '0945678901', 0, 'hoangvane@example.com', N'Thạc sĩ Chẩn đoán hình ảnh', 12, N'Bác sĩ Hoàng Văn E là một chuyên gia Chẩn đoán hình ảnh với bằng Thạc sĩ và 12 năm kinh nghiệm. Ông đã làm việc tại nhiều trung tâm y tế lớn và có kỹ năng thành thạo trong việc sử dụng các công nghệ hình ảnh hiện đại như MRI, CT scan, và siêu âm. Bác sĩ Hoàng Văn E luôn tìm kiếm và áp dụng các kỹ thuật mới nhất để nâng cao chất lượng chẩn đoán và điều trị cho bệnh nhân. Ông cũng là thành viên của nhiều hiệp hội chẩn đoán hình ảnh quốc tế và thường xuyên tham gia các hội nghị chuyên ngành để cập nhật các xu hướng mới trong lĩnh vực này.'),
(N'Ngô Thị F', 'password6', 1987, '0956789012', 1, 'ngothif@example.com', N'Tiến sĩ Da liễu', 9, N'Bác sĩ Ngô Thị F là một chuyên gia Da liễu với bằng Tiến sĩ và 9 năm kinh nghiệm. Bà đã công tác tại nhiều bệnh viện và trung tâm da liễu uy tín, chuyên về chẩn đoán và điều trị các bệnh lý da liễu như mụn trứng cá, viêm da cơ địa, bệnh vảy nến và các bệnh nhiễm trùng da. Bà luôn chú trọng đến việc cung cấp dịch vụ chăm sóc da chất lượng cao và cá nhân hóa cho từng bệnh nhân. Bà cũng thường xuyên tham gia các khóa đào tạo và hội thảo chuyên ngành để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Đặng Văn G', 'password7', 1975, '0967890123', 0, 'dangvang@example.com', N'Thạc sĩ Thần kinh học', 20, N'Bác sĩ Đặng Văn G là một chuyên gia Thần kinh học với bằng Thạc sĩ và 20 năm kinh nghiệm. Ông đã làm việc tại nhiều bệnh viện lớn và có kinh nghiệm phong phú trong việc chẩn đoán và điều trị các bệnh lý thần kinh như đột quỵ, bệnh Parkinson, bệnh Alzheimer và các bệnh lý thần kinh cơ. Bác sĩ Đặng Văn G luôn chú trọng đến việc cung cấp dịch vụ chăm sóc toàn diện và cá nhân hóa cho từng bệnh nhân. Ông cũng thường xuyên tham gia các hội nghị chuyên ngành và các khóa đào tạo để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Phan Thị H', 'password8', 1992, '0978901234', 1, 'phanthih@example.com', N'Tiến sĩ Phụ khoa', 6, N'Bác sĩ Phan Thị H là một chuyên gia Phụ khoa với bằng Tiến sĩ và 6 năm kinh nghiệm. Bà đã làm việc tại nhiều bệnh viện và trung tâm y tế lớn, chuyên về chẩn đoán và điều trị các bệnh lý phụ khoa như viêm nhiễm phụ khoa, rối loạn kinh nguyệt, và các bệnh lý ung thư phụ khoa. Bà luôn chú trọng đến việc cung cấp dịch vụ chăm sóc phụ khoa chất lượng cao và cá nhân hóa cho từng bệnh nhân. Bà cũng thường xuyên tham gia các khóa đào tạo và hội thảo chuyên ngành để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Trịnh Văn I', 'password9', 1983, '0989012345', 0, 'trinhvani@example.com', N'Thạc sĩ Tiêu hóa', 11, N'Bác sĩ Trịnh Văn I là một chuyên gia Tiêu hóa với bằng Thạc sĩ và 11 năm kinh nghiệm. Ông đã làm việc tại nhiều bệnh viện và trung tâm y tế lớn, chuyên về chẩn đoán và điều trị các bệnh lý tiêu hóa như viêm loét dạ dày, bệnh Crohn, và bệnh gan. Bác sĩ Trịnh Văn I luôn chú trọng đến việc cung cấp dịch vụ chăm sóc tiêu hóa chất lượng cao và cá nhân hóa cho từng bệnh nhân. Ông cũng thường xuyên tham gia các hội nghị chuyên ngành và các khóa đào tạo để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Hồ Thị J', 'password10', 1984, '0990123456', 1, 'hothij@example.com', N'Thạc sĩ Hô hấp', 10, N'Bác sĩ Hồ Thị J là một chuyên gia Hô hấp với bằng Thạc sĩ và 10 năm kinh nghiệm. Bà đã làm việc tại nhiều bệnh viện lớn và có kinh nghiệm phong phú trong việc chẩn đoán và điều trị các bệnh lý hô hấp như hen suyễn, viêm phổi, và bệnh phổi tắc nghẽn mạn tính (COPD). Bác sĩ Hồ Thị J luôn chú trọng đến việc cung cấp dịch vụ chăm sóc hô hấp chất lượng cao và cá nhân hóa cho từng bệnh nhân. Bà cũng thường xuyên tham gia các hội nghị chuyên ngành và các khóa đào tạo để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Vũ Văn K', 'password11', 1979, '0901234567', 0, 'vuvank@example.com', N'Tiến sĩ Dị ứng và miễn dịch', 15, N'Bác sĩ Vũ Văn K là một chuyên gia Dị ứng và miễn dịch với bằng Tiến sĩ và 15 năm kinh nghiệm. Ông đã làm việc tại nhiều bệnh viện và trung tâm y tế lớn, chuyên về chẩn đoán và điều trị các bệnh lý dị ứng như viêm mũi dị ứng, hen suyễn dị ứng, và các bệnh lý tự miễn. Bác sĩ Vũ Văn K luôn chú trọng đến việc cung cấp dịch vụ chăm sóc dị ứng và miễn dịch chất lượng cao và cá nhân hóa cho từng bệnh nhân. Ông cũng thường xuyên tham gia các hội nghị chuyên ngành và các khóa đào tạo để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Nguyễn Thị L', 'password12', 1991, '0912345670', 1, 'nguyenthil@example.com', N'Thạc sĩ Tâm lý học lâm sàng', 7, N'Bác sĩ Nguyễn Thị L là một chuyên gia Tâm lý học lâm sàng với bằng Thạc sĩ và 7 năm kinh nghiệm. Bà đã làm việc tại nhiều bệnh viện và trung tâm tâm lý uy tín, chuyên về chẩn đoán và điều trị các rối loạn tâm lý như trầm cảm, lo âu, rối loạn lưỡng cực và các rối loạn tâm thần khác. Bà luôn chú trọng đến việc cung cấp dịch vụ chăm sóc tâm lý chất lượng cao và cá nhân hóa cho từng bệnh nhân. Bà cũng thường xuyên tham gia các hội nghị chuyên ngành và các khóa đào tạo để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Trương Văn M', 'password13', 1986, '0923456781', 0, 'truongvanm@example.com', N'Tiến sĩ Chỉnh hình', 10, N'Bác sĩ Trương Văn M là một chuyên gia Chỉnh hình với bằng Tiến sĩ và 10 năm kinh nghiệm. Ông đã làm việc tại nhiều bệnh viện lớn và có kinh nghiệm phong phú trong việc chẩn đoán và điều trị các bệnh lý chỉnh hình như gãy xương, thoái hóa khớp, và các bệnh lý cột sống. Bác sĩ Trương Văn M luôn chú trọng đến việc cung cấp dịch vụ chăm sóc chỉnh hình chất lượng cao và cá nhân hóa cho từng bệnh nhân. Ông cũng thường xuyên tham gia các hội nghị chuyên ngành và các khóa đào tạo để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Phạm Thị N', 'password14', 1988, '0934567892', 1, 'phamthin@example.com', N'Thạc sĩ Dinh dưỡng', 8, N'Bác sĩ Phạm Thị N là một chuyên gia Dinh dưỡng với bằng Thạc sĩ và 8 năm kinh nghiệm. Bà đã làm việc tại nhiều bệnh viện và trung tâm dinh dưỡng uy tín, chuyên về chẩn đoán và điều trị các vấn đề dinh dưỡng như suy dinh dưỡng, béo phì, và các bệnh lý liên quan đến chế độ ăn uống. Bà luôn chú trọng đến việc cung cấp dịch vụ chăm sóc dinh dưỡng chất lượng cao và cá nhân hóa cho từng bệnh nhân. Bà cũng thường xuyên tham gia các hội nghị chuyên ngành và các khóa đào tạo để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Đỗ Văn O', 'password15', 1985, '0945678903', 0, 'dovano@example.com', N'Thạc sĩ Ung bướu', 9, N'Bác sĩ Đỗ Văn O là một chuyên gia Ung bướu với bằng Thạc sĩ và 9 năm kinh nghiệm. Ông đã làm việc tại nhiều bệnh viện và trung tâm ung bướu uy tín, chuyên về chẩn đoán và điều trị các bệnh lý ung thư như ung thư vú, ung thư phổi, và ung thư đường tiêu hóa. Bác sĩ Đỗ Văn O luôn chú trọng đến việc cung cấp dịch vụ chăm sóc ung bướu chất lượng cao và cá nhân hóa cho từng bệnh nhân. Ông cũng thường xuyên tham gia các hội nghị chuyên ngành và các khóa đào tạo để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Nguyễn Thị P', 'password16', 1993, '0956789014', 1, 'nguyenthip@example.com', N'Thạc sĩ Y học gia đình', 6, N'Bác sĩ Nguyễn Thị P là một chuyên gia Y học gia đình với bằng Thạc sĩ và 6 năm kinh nghiệm. Bà đã làm việc tại nhiều bệnh viện và trung tâm y tế lớn, chuyên về chẩn đoán và điều trị các bệnh lý thông thường và quản lý sức khỏe tổng quát cho các thành viên trong gia đình. Bà luôn chú trọng đến việc cung cấp dịch vụ chăm sóc y học gia đình chất lượng cao và cá nhân hóa cho từng bệnh nhân. Bà cũng thường xuyên tham gia các hội nghị chuyên ngành và các khóa đào tạo để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Lý Văn Q', 'password17', 1984, '0967890125', 0, 'lyvanq@example.com', N'Thạc sĩ Huyết học', 11, N'Bác sĩ Lý Văn Q là một chuyên gia Huyết học với bằng Thạc sĩ và 11 năm kinh nghiệm. Ông đã làm việc tại nhiều bệnh viện và trung tâm huyết học lớn, chuyên về chẩn đoán và điều trị các bệnh lý huyết học như thiếu máu, bệnh bạch cầu, và các rối loạn đông máu. Bác sĩ Lý Văn Q luôn chú trọng đến việc cung cấp dịch vụ chăm sóc huyết học chất lượng cao và cá nhân hóa cho từng bệnh nhân. Ông cũng thường xuyên tham gia các hội nghị chuyên ngành và các khóa đào tạo để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Tạ Thị R', 'password18', 1990, '0978901236', 1, 'tatheir@example.com', N'Thạc sĩ Sản phụ khoa', 8, N'Bác sĩ Tạ Thị R là một chuyên gia Sản phụ khoa với bằng Thạc sĩ và 8 năm kinh nghiệm. Bà đã làm việc tại nhiều bệnh viện và trung tâm sản phụ khoa lớn, chuyên về chẩn đoán và điều trị các bệnh lý sản phụ khoa như viêm nhiễm phụ khoa, rối loạn kinh nguyệt, và các bệnh lý ung thư phụ khoa. Bà luôn chú trọng đến việc cung cấp dịch vụ chăm sóc sản phụ khoa chất lượng cao và cá nhân hóa cho từng bệnh nhân. Bà cũng thường xuyên tham gia các hội nghị chuyên ngành và các khóa đào tạo để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Bùi Văn S', 'password19', 1981, '0989012347', 0, 'buivans@example.com', N'Tiến sĩ Nhi khoa', 14, N'Bác sĩ Bùi Văn S là một chuyên gia Nhi khoa với bằng Tiến sĩ và 14 năm kinh nghiệm. Ông đã làm việc tại nhiều bệnh viện lớn và có kinh nghiệm phong phú trong việc chăm sóc và điều trị các bệnh nhi. Bác sĩ Bùi Văn S đặc biệt chú trọng đến việc theo dõi và quản lý sức khỏe của trẻ từ khi còn trong bụng mẹ đến khi trưởng thành. Ông luôn tận tâm với nghề, không ngừng học hỏi và áp dụng các phương pháp điều trị tiên tiến nhất để mang lại sức khỏe tốt nhất cho trẻ em. Ông cũng thường xuyên tham gia các hội thảo quốc tế và các khóa đào tạo chuyên sâu để nâng cao kiến thức và kỹ năng.'),
(N'Nguyễn Văn T', 'password20', 1977, '0990123458', 0, 'nguyenvant@example.com', N'Thạc sĩ Thần kinh học', 17, N'Bác sĩ Nguyễn Văn T là một chuyên gia Thần kinh học với bằng Thạc sĩ và 17 năm kinh nghiệm. Ông đã làm việc tại nhiều bệnh viện lớn và có kinh nghiệm phong phú trong việc chẩn đoán và điều trị các bệnh lý thần kinh như đột quỵ, bệnh Parkinson, bệnh Alzheimer và các bệnh lý thần kinh cơ. Bác sĩ Nguyễn Văn T luôn chú trọng đến việc cung cấp dịch vụ chăm sóc toàn diện và cá nhân hóa cho từng bệnh nhân. Ông cũng thường xuyên tham gia các hội nghị chuyên ngành và các khóa đào tạo để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Hoàng Thị U', 'password21', 1983, '0901234569', 1, 'hoangthiu@example.com', N'Thạc sĩ Phụ khoa', 12, N'Bác sĩ Hoàng Thị U là một chuyên gia Phụ khoa với bằng Thạc sĩ và 12 năm kinh nghiệm. Bà đã làm việc tại nhiều bệnh viện và trung tâm y tế lớn, chuyên về chẩn đoán và điều trị các bệnh lý phụ khoa như viêm nhiễm phụ khoa, rối loạn kinh nguyệt, và các bệnh lý ung thư phụ khoa. Bà luôn chú trọng đến việc cung cấp dịch vụ chăm sóc phụ khoa chất lượng cao và cá nhân hóa cho từng bệnh nhân. Bà cũng thường xuyên tham gia các khóa đào tạo và hội thảo chuyên ngành để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Phan Văn V', 'password22', 1986, '0912345672', 0, 'phanvanv@example.com', N'Thạc sĩ Nội tiết', 10, N'Bác sĩ Phan Văn V là một chuyên gia Nội tiết với bằng Thạc sĩ và 10 năm kinh nghiệm. Ông đã làm việc tại nhiều bệnh viện lớn và có kinh nghiệm phong phú trong việc chẩn đoán và điều trị các bệnh lý nội tiết như tiểu đường, bệnh tuyến giáp, và các rối loạn nội tiết khác. Bác sĩ Phan Văn V luôn chú trọng đến việc cung cấp dịch vụ chăm sóc nội tiết chất lượng cao và cá nhân hóa cho từng bệnh nhân. Ông cũng thường xuyên tham gia các hội nghị chuyên ngành và các khóa đào tạo để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Võ Thị X', 'password23', 1990, '0923456783', 1, 'vothix@example.com', N'Thạc sĩ Răng hàm mặt', 8, N'Bác sĩ Võ Thị X là một chuyên gia Răng hàm mặt với bằng Thạc sĩ và 8 năm kinh nghiệm. Bà đã làm việc tại nhiều bệnh viện và trung tâm y tế lớn, chuyên về chẩn đoán và điều trị các bệnh lý răng hàm mặt như sâu răng, viêm nướu, và các bệnh lý hàm mặt khác. Bà luôn chú trọng đến việc cung cấp dịch vụ chăm sóc răng hàm mặt chất lượng cao và cá nhân hóa cho từng bệnh nhân. Bà cũng thường xuyên tham gia các khóa đào tạo và hội thảo chuyên ngành để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Đặng Văn Y', 'password24', 1984, '0934567894', 0, 'dangvany@example.com', N'Thạc sĩ Cơ xương khớp', 11, N'Bác sĩ Đặng Văn Y là một chuyên gia Cơ xương khớp với bằng Thạc sĩ và 11 năm kinh nghiệm. Ông đã làm việc tại nhiều bệnh viện và trung tâm y tế lớn, chuyên về chẩn đoán và điều trị các bệnh lý cơ xương khớp như viêm khớp, thoái hóa khớp, và loãng xương. Bác sĩ Đặng Văn Y luôn chú trọng đến việc cung cấp dịch vụ chăm sóc cơ xương khớp chất lượng cao và cá nhân hóa cho từng bệnh nhân. Ông cũng thường xuyên tham gia các hội nghị chuyên ngành và các khóa đào tạo để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Trần Thị Z', 'password25', 1989, '0945678905', 1, 'tranthiz@example.com', N'Thạc sĩ Tâm thần học', 9, N'Bác sĩ Trần Thị Z là một chuyên gia Tâm thần học với bằng Thạc sĩ và 9 năm kinh nghiệm. Bà đã làm việc tại nhiều bệnh viện và trung tâm tâm thần uy tín, chuyên về chẩn đoán và điều trị các rối loạn tâm thần như trầm cảm, lo âu, rối loạn lưỡng cực và các rối loạn tâm thần khác. Bà luôn chú trọng đến việc cung cấp dịch vụ chăm sóc tâm thần chất lượng cao và cá nhân hóa cho từng bệnh nhân. Bà cũng thường xuyên tham gia các hội nghị chuyên ngành và các khóa đào tạo để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Ngô Văn AA', 'password26', 1982, '0956789016', 0, 'ngovanaa@example.com', N'Thạc sĩ Y học thể thao', 13, N'Bác sĩ Ngô Văn AA là một chuyên gia Y học thể thao với bằng Thạc sĩ và 13 năm kinh nghiệm. Ông đã làm việc tại nhiều bệnh viện và trung tâm y tế lớn, chuyên về chẩn đoán và điều trị các chấn thương thể thao như bong gân, trật khớp, và các vấn đề về cơ xương khớp do hoạt động thể thao. Bác sĩ Ngô Văn AA luôn chú trọng đến việc cung cấp dịch vụ chăm sóc y học thể thao chất lượng cao và cá nhân hóa cho từng bệnh nhân. Ông cũng thường xuyên tham gia các hội nghị chuyên ngành và các khóa đào tạo để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Bùi Thị BB', 'password27', 1987, '0967890127', 1, 'buithibb@example.com', N'Thạc sĩ Dược học', 10, N'Bác sĩ Bùi Thị BB là một chuyên gia Dược học với bằng Thạc sĩ và 10 năm kinh nghiệm. Bà đã làm việc tại nhiều bệnh viện và trung tâm y tế lớn, chuyên về chẩn đoán và điều trị các bệnh lý liên quan đến dược phẩm như dị ứng thuốc, tương tác thuốc, và các tác dụng phụ của thuốc. Bà luôn chú trọng đến việc cung cấp dịch vụ chăm sóc dược học chất lượng cao và cá nhân hóa cho từng bệnh nhân. Bà cũng thường xuyên tham gia các hội nghị chuyên ngành và các khóa đào tạo để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Đoàn Văn CC', 'password28', 1980, '0978901238', 0, 'doanvancc@example.com', N'Thạc sĩ Bệnh lý nhiễm trùng', 14, N'Bác sĩ Đoàn Văn CC là một chuyên gia Bệnh lý nhiễm trùng với bằng Thạc sĩ và 14 năm kinh nghiệm. Ông đã làm việc tại nhiều bệnh viện lớn và có kinh nghiệm phong phú trong việc chẩn đoán và điều trị các bệnh lý nhiễm trùng như viêm phổi, viêm gan, và các bệnh truyền nhiễm khác. Bác sĩ Đoàn Văn CC luôn chú trọng đến việc cung cấp dịch vụ chăm sóc bệnh lý nhiễm trùng chất lượng cao và cá nhân hóa cho từng bệnh nhân. Ông cũng thường xuyên tham gia các hội nghị chuyên ngành và các khóa đào tạo để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Trịnh Thị DD', 'password29', 1986, '0989012349', 1, 'trinhthidd@example.com', N'Thạc sĩ Phục hồi chức năng', 12, N'Bác sĩ Trịnh Thị DD là một chuyên gia Phục hồi chức năng với bằng Thạc sĩ và 12 năm kinh nghiệm. Bà đã làm việc tại nhiều bệnh viện và trung tâm phục hồi chức năng lớn, chuyên về chẩn đoán và điều trị các bệnh lý cần phục hồi chức năng như đột quỵ, tai nạn giao thông, và các bệnh lý cơ xương khớp. Bà luôn chú trọng đến việc cung cấp dịch vụ chăm sóc phục hồi chức năng chất lượng cao và cá nhân hóa cho từng bệnh nhân. Bà cũng thường xuyên tham gia các hội nghị chuyên ngành và các khóa đào tạo để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.'),
(N'Vũ Văn EE', 'password30', 1978, '0990123450', 0, 'vuvanee@example.com', N'Tiến sĩ Hóa sinh', 18, N'Bác sĩ Vũ Văn EE là một chuyên gia Hóa sinh với bằng Tiến sĩ và 18 năm kinh nghiệm. Ông đã làm việc tại nhiều bệnh viện và trung tâm nghiên cứu lớn, chuyên về chẩn đoán và điều trị các bệnh lý liên quan đến hóa sinh như bệnh di truyền, các rối loạn chuyển hóa, và các bệnh lý về enzym. Bác sĩ Vũ Văn EE luôn chú trọng đến việc cung cấp dịch vụ chăm sóc hóa sinh chất lượng cao và cá nhân hóa cho từng bệnh nhân. Ông cũng thường xuyên tham gia các hội nghị chuyên ngành và các khóa đào tạo để cập nhật kiến thức và nâng cao kỹ năng chuyên môn.');


-- Insert sample data into BenhNhan table
INSERT INTO BenhNhan (hoten, username, [password], namSinh, diaChi, SDT, gioiTinh, email) VALUES
(N'Nguyễn Văn A', 'nguyenvana', 'password1', 1980, N'123 Đường ABC, Quận 1', '0123456789', 0, 'nguyenvana@example.com'),
(N'Trần Thị B', 'tranthib', 'password2', 1981, N'456 Đường DEF, Quận 2', '0987654321', 1, 'tranthib@example.com'),
(N'Lê Văn C', 'levanc', 'password3', 1982, N'789 Đường GHI, Quận 3', '0123456780', 0, 'levanc@example.com'),
(N'Phạm Thị D', 'phamthid', 'password4', 1983, N'012 Đường JKL, Quận 4', '0987654321', 1, 'phamthid@example.com'),
(N'Hồ Văn E', 'hovane', 'password5', 1984, N'345 Đường MNO, Quận 5', '0123456789', 0, 'hovane@example.com'),
(N'Đặng Thị F', 'dangthif', 'password6', 1985, N'678 Đường PQR, Quận 6', '0987654321', 1, 'dangthif@example.com'),
(N'Vũ Văn G', 'vuvang', 'password7', 1986, N'901 Đường STU, Quận 7', '0123456789', 0, 'vuvang@example.com'),
(N'Bùi Thị H', 'buithih', 'password8', 1987, N'234 Đường VWX, Quận 8', '0987654321', 1, 'buithih@example.com'),
(N'Hoàng Văn I', 'hoangvani', 'password9', 1988, N'567 Đường YZ, Quận 9', '0123456789', 0, 'hoangvani@example.com'),
(N'Nguyễn Thị K', 'nguyenthiK', 'password10', 1989, N'890 Đường ABC, Quận 10', '0987654321', 1, 'nguyenthiK@example.com'),
(N'Trần Văn L', 'tranvanl', 'password11', 1990, N'123 Đường DEF, Quận 11', '0123456789', 0, 'tranvanl@example.com'),
(N'Lê Thị M', 'lethim', 'password12', 1991, N'456 Đường GHI, Quận 12', '0987654321', 1, 'lethim@example.com'),
(N'Phạm Văn N', 'phamvann', 'password13', 1992, N'789 Đường JKL, Quận Bình Thạnh', '0123456789', 0, 'phamvann@example.com'),
(N'Hồ Thị P', 'hothip', 'password14', 1993, N'012 Đường MNO, Quận Gò Vấp', '0987654321', 1, 'hothip@example.com'),
(N'Đặng Văn Q', 'dangvanq', 'password15', 1994, N'345 Đường PQRS, Quận Tân Bình', '0123456789', 0, 'dangvanq@example.com'),
(N'Vũ Thị R', 'vuthir', 'password16', 1995, N'678 Đường TUV, Quận Tân Phú', '0987654321', 1, 'vuthir@example.com'),
(N'Bùi Văn S', 'buivans', 'password17', 1996, N'901 Đường WXYZ, Quận Phú Nhuận', '0123456789', 0, 'buivans@example.com'),
(N'Hoàng Thị T', 'hoangthit', 'password18', 1997, N'234 Đường ABC, Quận 1', '0987654321', 1, 'hoangthit@example.com'),
(N'Nguyễn Văn U', 'nguyenvanu', 'password19', 1998, N'567 Đường DEF, Quận 2', '0123456789', 0, 'nguyenvanu@example.com'),
(N'Trần Thị V', 'tranthiv', 'password20', 1999, N'890 Đường GHI, Quận 3', '0987654321', 1, 'tranthiv@example.com'),
(N'Lê Văn X', 'levanx', 'password21', 2000, N'123 Đường JKL, Quận 4', '0123456789', 0, 'levanx@example.com'),
(N'Phạm Thị Y', 'phamthiy', 'password22', 2001, N'456 Đường MNO, Quận 5', '0987654321', 1, 'phamthiy@example.com'),
(N'Hồ Văn Z', 'hovanz', 'password23', 2002, N'789 Đường PQR, Quận 6', '0123456789', 0, 'hovanz@example.com'),
(N'Đặng Thị W', 'dangthiw', 'password24', 2003, N'901 Đường STU, Quận 7', '0987654321', 1, 'dangthiw@example.com'),
(N'Vũ Văn H', 'vuvanh', 'password25', 2004, N'234 Đường VWX, Quận 8', '0123456789', 0, 'vuvanh@example.com'),
(N'Bùi Thị I', 'buithii', 'password26', 2005, N'567 Đường YZ, Quận 9', '0987654321', 1, 'buithii@example.com'),
(N'Hoàng Văn J', 'hoangvanj', 'password27', 2006, N'890 Đường ABC, Quận 10', '0123456789', 0, 'hoangvanj@example.com');


-- Insert sample data into CaKham table
INSERT INTO CaKham (KhungGio) VALUES
(N'08:00 - 09:00'),
(N'09:00 - 10:00'),
(N'10:00 - 11:00'),
(N'13:00 - 14:00'),
(N'14:00 - 15:00'),
(N'15:00 - 16:00');

-- Insert sample data into BacsiKhoa table
INSERT INTO BacsiKhoa (IDBacSi, IDKhoa, ChucVu)
VALUES 
('BS000001', 1, N'Trưởng khoa'),
('BS000002', 1, N'Phó Khoa'),
('BS000003', 1, N'Bác sĩ'),
('BS000004', 2, N'Trưởng khoa'),
('BS000005', 2, N'Phó Khoa'),
('BS000006', 2, N'Bác sĩ'),
('BS000007', 3, N'Trưởng khoa'),
('BS000008', 3, N'Phó Khoa'),
('BS000009', 3, N'Bác sĩ'),
('BS000010', 4, N'Trưởng khoa'),
('BS000011', 4, N'Phó Khoa'),
('BS000012', 4, N'Bác sĩ'),
('BS000013', 5, N'Trưởng khoa'),
('BS000014', 5, N'Phó Khoa'),
('BS000015', 5, N'Bác sĩ'),
('BS000016', 6, N'Trưởng khoa'),
('BS000017', 6, N'Phó Khoa'),
('BS000018', 6, N'Bác sĩ'),
('BS000019', 7, N'Trưởng khoa'),
('BS000020', 7, N'Phó Khoa'),
('BS000021', 7, N'Bác sĩ'),
('BS000022', 8, N'Trưởng khoa'),
('BS000023', 8, N'Phó Khoa'),
('BS000024', 8, N'Bác sĩ'),
('BS000025', 9, N'Trưởng khoa'),
('BS000026', 9, N'Phó Khoa'),
('BS000027', 9, N'Bác sĩ'),
('BS000028', 10, N'Trưởng khoa'),
('BS000029', 10, N'Phó Khoa'),
('BS000030', 10, N'Bác sĩ');


-- Insert sample data into LichLamViec table
INSERT INTO LichLamViec (IDBacSi, IDKhoa, IDCa, Thu) VALUES
('BS000001', 1, 1, 2), -- Thứ 2
('BS000001', 1, 2, 2), -- Thứ 2
('BS000001', 1, 3, 3), -- Thứ 3
('BS000002', 2, 4, 4), -- Thứ 4
('BS000002', 2, 5, 5); -- Thứ 5

-- Insert sample data into DichVu table
INSERT INTO DichVu (IDKhoa, TenDichVu, GiaKham, MoTa)
VALUES 
(1, N'Khám tim mạch cơ bản', 500000, N'Khám tim mạch cơ bản là một quy trình y khoa toàn diện nhằm kiểm tra và đánh giá sức khỏe tim mạch của bệnh nhân. Bác sĩ sẽ tiến hành một loạt các kiểm tra lâm sàng, bao gồm đo huyết áp, kiểm tra nhịp tim, nghe tim phổi, và đánh giá các triệu chứng lâm sàng. Quy trình này có thể bao gồm tiền sử bệnh, tiền sử gia đình, thói quen sinh hoạt và các yếu tố nguy cơ khác. Kết quả của khám tim mạch cơ bản giúp phát hiện sớm các vấn đề về tim mạch như tăng huyết áp, rối loạn nhịp tim, bệnh mạch vành và đề xuất các biện pháp phòng ngừa hoặc điều trị kịp thời.'),
(1, N'Điện tâm đồ', 200000, N'Điện tâm đồ (ECG) là một kỹ thuật y học sử dụng để ghi lại các hoạt động điện của tim trong một khoảng thời gian ngắn. Trong quá trình này, các điện cực sẽ được gắn trên ngực, cánh tay và chân của bệnh nhân để thu thập các tín hiệu điện từ tim. Những tín hiệu này được ghi lại dưới dạng đồ thị, giúp bác sĩ phân tích và đánh giá chức năng điện học của tim. Điện tâm đồ có thể phát hiện các bất thường như nhồi máu cơ tim, loạn nhịp, tăng kích thước các buồng tim và các bệnh lý tim mạch khác, từ đó hỗ trợ trong việc chẩn đoán và điều trị.'),
(1, N'Siêu âm tim', 400000, N'Siêu âm tim là một phương pháp chẩn đoán hình ảnh không xâm lấn sử dụng sóng siêu âm để tạo ra hình ảnh chi tiết về cấu trúc và chức năng của tim. Trong quá trình này, một đầu dò siêu âm được đặt trên ngực của bệnh nhân, phát ra sóng âm thanh và thu nhận các tín hiệu phản xạ từ các mô tim. Hình ảnh thu được cung cấp thông tin về kích thước, hình dạng, và chuyển động của các buồng tim, van tim, và dòng máu chảy qua tim. Siêu âm tim giúp bác sĩ phát hiện các bất thường như hẹp van, hở van, tim bẩm sinh, và các bệnh lý khác liên quan đến cấu trúc và chức năng của tim.'),
(1, N'Test gắng sức', 600000, N'Test gắng sức là một phương pháp chẩn đoán được sử dụng để đánh giá khả năng hoạt động của tim khi bệnh nhân thực hiện các bài tập thể dục gắng sức. Trong quá trình này, bệnh nhân sẽ đi bộ hoặc chạy trên băng chuyền hoặc đạp xe đạp cố định trong khi các chỉ số như nhịp tim, huyết áp, và điện tâm đồ được theo dõi liên tục. Test gắng sức giúp phát hiện các vấn đề về tim mạch như bệnh mạch vành, suy tim, loạn nhịp, và đánh giá hiệu quả của các biện pháp điều trị hiện tại. Kết quả của test gắng sức cung cấp thông tin quan trọng về khả năng chịu đựng của tim và mức độ an toàn khi thực hiện các hoạt động thể chất.'),
(1, N'Tư vấn chế độ dinh dưỡng', 300000, N'Tư vấn chế độ dinh dưỡng là dịch vụ cung cấp các hướng dẫn và khuyến nghị về chế độ ăn uống và lối sống nhằm cải thiện sức khỏe tim mạch của bệnh nhân. Các chuyên gia dinh dưỡng sẽ đánh giá tình trạng sức khỏe hiện tại, tiền sử bệnh lý, và thói quen ăn uống của bệnh nhân để đề xuất các thay đổi cần thiết. Chế độ dinh dưỡng có thể bao gồm việc tăng cường các loại thực phẩm giàu dinh dưỡng, giảm muối, chất béo bão hòa, và đường, đồng thời khuyến khích hoạt động thể chất đều đặn. Tư vấn dinh dưỡng giúp bệnh nhân xây dựng lối sống lành mạnh, giảm nguy cơ mắc các bệnh tim mạch, và cải thiện chất lượng cuộc sống.'),
(2, N'Phẫu thuật bắc cầu động mạch vành', 20000000, N'Phẫu thuật bắc cầu động mạch vành là một quy trình phẫu thuật nhằm tái lưu thông máu qua các động mạch vành bị tắc nghẽn. Trong quá trình này, các bác sĩ phẫu thuật sẽ sử dụng một đoạn mạch máu từ một phần khác của cơ thể để tạo ra một đường dẫn mới, bypass (bắc cầu) qua đoạn động mạch bị tắc. Phẫu thuật này giúp cải thiện dòng máu đến cơ tim, giảm triệu chứng đau thắt ngực và ngăn ngừa nhồi máu cơ tim. Quá trình phục hồi sau phẫu thuật bao gồm việc theo dõi chặt chẽ và tuân thủ các hướng dẫn y khoa để đảm bảo sức khỏe tim mạch tốt nhất cho bệnh nhân.'),
(2, N'Phẫu thuật thay van tim', 25000000, N'Phẫu thuật thay van tim là một quy trình phẫu thuật quan trọng nhằm thay thế các van tim bị hỏng bằng các van nhân tạo hoặc van từ động vật. Quy trình này thường được thực hiện khi các van tim bị hẹp hoặc hở gây ra các triệu chứng nghiêm trọng như khó thở, mệt mỏi, và đau ngực. Phẫu thuật thay van giúp khôi phục lưu thông máu bình thường qua tim, cải thiện chức năng tim và chất lượng cuộc sống của bệnh nhân. Sau phẫu thuật, bệnh nhân cần được theo dõi và chăm sóc đặc biệt để đảm bảo sự hoạt động ổn định của van tim mới và ngăn ngừa các biến chứng.'),
(2, N'Phẫu thuật sửa chữa thông liên nhĩ', 15000000, N'Phẫu thuật sửa chữa thông liên nhĩ là quy trình phẫu thuật để điều trị các lỗ thông liên nhĩ, một loại dị tật tim bẩm sinh. Lỗ thông liên nhĩ là một lỗ hở bất thường giữa hai buồng nhĩ của tim, cho phép máu chảy tự do giữa hai bên, gây ra các vấn đề về tuần hoàn và tăng áp lực động mạch phổi. Trong quá trình phẫu thuật, bác sĩ sẽ sử dụng một miếng vá hoặc khâu lại lỗ thông để ngăn chặn sự chảy máu bất thường. Phẫu thuật này giúp cải thiện lưu thông máu, giảm triệu chứng và ngăn ngừa các biến chứng nghiêm trọng.'),
(2, N'Phẫu thuật động mạch chủ', 22000000, N'Phẫu thuật động mạch chủ là một quy trình phẫu thuật phức tạp để điều trị các vấn đề về động mạch chủ, chẳng hạn như phình động mạch chủ, hẹp động mạch chủ hoặc bóc tách động mạch chủ. Trong quá trình này, bác sĩ sẽ loại bỏ phần động mạch bị tổn thương và thay thế bằng một đoạn mạch nhân tạo. Quy trình này giúp ngăn ngừa các biến chứng nguy hiểm như vỡ động mạch, suy tim, và đột quỵ. Sau phẫu thuật, bệnh nhân cần được theo dõi chặt chẽ và tuân thủ các chỉ dẫn của bác sĩ để đảm bảo sự phục hồi tốt nhất.'),
(2, N'Phẫu thuật tim kín', 18000000, N'Phẫu thuật tim kín là các quy trình phẫu thuật được thực hiện mà không cần mở ngực hoặc tim hoàn toàn. Các thủ thuật này thường được sử dụng để điều trị các vấn đề tim mạch ít phức tạp hoặc làm cầu nối đến các phẫu thuật tim mở. Ví dụ, các thủ thuật này có thể bao gồm đặt stent, bít lỗ thông, hoặc sửa chữa các cấu trúc tim nhỏ. Phẫu thuật tim kín thường có thời gian phục hồi ngắn hơn và ít nguy cơ biến chứng hơn so với phẫu thuật tim mở.'),
(3, N'Xét nghiệm máu', 200000, N'Xét nghiệm máu là một trong những phương pháp cơ bản và quan trọng trong chẩn đoán y khoa, giúp phân tích các thành phần trong máu để đánh giá tình trạng sức khỏe của bệnh nhân. Các xét nghiệm máu thông thường bao gồm đo lường các chỉ số như số lượng hồng cầu, bạch cầu, tiểu cầu, hemoglobin, và các chất hóa học như đường huyết, cholesterol, và các enzyme. Kết quả của xét nghiệm máu có thể giúp phát hiện sớm các bệnh lý như thiếu máu, nhiễm trùng, rối loạn chuyển hóa, và các bệnh tim mạch, từ đó hỗ trợ bác sĩ trong việc đề xuất các biện pháp điều trị phù hợp.'),
(3, N'Chụp CT tim', 500000, N'Chụp CT tim là kỹ thuật chụp cắt lớp vi tính sử dụng tia X để tạo ra hình ảnh chi tiết về cấu trúc và mạch máu của tim. Quá trình này bao gồm việc tiêm chất cản quang vào tĩnh mạch để làm nổi bật các mạch máu trong hình ảnh. Chụp CT tim giúp phát hiện và đánh giá các vấn đề như tắc nghẽn động mạch vành, phình động mạch, bệnh van tim, và các dị tật tim bẩm sinh. Kỹ thuật này cung cấp thông tin quan trọng giúp bác sĩ đưa ra chẩn đoán chính xác và lập kế hoạch điều trị hiệu quả cho bệnh nhân.'),
(3, N'Chụp MRI tim', 700000, N'Chụp MRI tim là kỹ thuật chẩn đoán hình ảnh tiên tiến sử dụng từ trường mạnh và sóng radio để tạo ra hình ảnh chi tiết và rõ nét về cấu trúc và chức năng của tim. Không giống như chụp CT, MRI không sử dụng tia X, do đó giảm thiểu nguy cơ phơi nhiễm phóng xạ. Chụp MRI tim giúp phát hiện và đánh giá các vấn đề như bệnh cơ tim, bệnh van tim, khối u tim, và các dị tật bẩm sinh. Kết quả của chụp MRI tim cung cấp thông tin chính xác về tình trạng tim mạch, hỗ trợ bác sĩ trong việc chẩn đoán và điều trị.'),
(3, N'Thở máy', 800000, N'Thở máy là một phương pháp hỗ trợ hô hấp quan trọng được sử dụng cho các bệnh nhân gặp khó khăn trong việc tự thở, đặc biệt là trong các tình huống cấp cứu hoặc sau các phẫu thuật phức tạp. Máy thở sẽ cung cấp không khí hoặc hỗn hợp khí, bao gồm cả oxy, vào phổi của bệnh nhân thông qua một ống đặt vào khí quản hoặc mặt nạ. Thở máy giúp duy trì mức oxy và carbon dioxide ổn định trong máu, đảm bảo các cơ quan trong cơ thể hoạt động bình thường. Quá trình này yêu cầu giám sát liên tục để điều chỉnh các thông số máy thở phù hợp với tình trạng của bệnh nhân.'),
(3, N'Tiêu sợi huyết', 1000000, N'Tiêu sợi huyết là phương pháp điều trị sử dụng các thuốc tiêu huyết khối để phá vỡ các cục máu đông trong mạch máu, đặc biệt trong các trường hợp đột quỵ, nhồi máu cơ tim, hoặc tắc mạch phổi. Quá trình tiêu sợi huyết giúp khôi phục lưu thông máu đến các cơ quan bị ảnh hưởng, giảm thiểu tổn thương và ngăn ngừa các biến chứng nghiêm trọng. Thuốc tiêu sợi huyết thường được tiêm tĩnh mạch và yêu cầu theo dõi chặt chẽ để đảm bảo hiệu quả và an toàn trong điều trị.'),
(4, N'Khám tim mạch trẻ em', 400000, N'Khám tim mạch trẻ em là quá trình kiểm tra và đánh giá tình trạng tim mạch của trẻ em. Các bác sĩ sẽ thực hiện các kiểm tra lâm sàng như đo nhịp tim, huyết áp, nghe tim phổi và có thể yêu cầu các xét nghiệm bổ sung như điện tâm đồ hoặc siêu âm tim. Mục tiêu của khám tim mạch trẻ em là phát hiện sớm các dị tật bẩm sinh, bệnh lý tim mạch và đưa ra các biện pháp điều trị phù hợp để bảo vệ sức khỏe tim mạch của trẻ.'),
(4, N'Siêu âm tim trẻ em', 450000, N'Siêu âm tim trẻ em là phương pháp sử dụng sóng siêu âm để tạo ra hình ảnh chi tiết về cấu trúc và chức năng của tim ở trẻ em. Quá trình này tương tự như siêu âm tim ở người lớn nhưng được điều chỉnh để phù hợp với cơ thể nhỏ bé của trẻ. Siêu âm tim trẻ em giúp phát hiện các dị tật bẩm sinh như thông liên nhĩ, thông liên thất, hẹp van động mạch và các vấn đề khác liên quan đến tim mạch. Kỹ thuật này không xâm lấn và an toàn cho trẻ, cung cấp thông tin chính xác để hỗ trợ chẩn đoán và điều trị.'),
(4, N'Tư vấn tim mạch trẻ em', 350000, N'Tư vấn tim mạch trẻ em là dịch vụ cung cấp các hướng dẫn và khuyến nghị về chăm sóc sức khỏe tim mạch cho trẻ em và gia đình. Các bác sĩ chuyên khoa sẽ đánh giá tình trạng tim mạch của trẻ, xem xét tiền sử bệnh lý, và đưa ra các khuyến nghị về chế độ ăn uống, hoạt động thể chất và lối sống lành mạnh. Tư vấn tim mạch giúp phụ huynh hiểu rõ hơn về tình trạng sức khỏe của con mình, các biện pháp phòng ngừa và điều trị, từ đó hỗ trợ tối ưu sự phát triển và sức khỏe tim mạch của trẻ.'),
(4, N'Xét nghiệm máu trẻ em', 250000, N'Xét nghiệm máu trẻ em là quá trình lấy mẫu máu của trẻ để phân tích các chỉ số sinh hóa và huyết học. Các xét nghiệm này giúp đánh giá sức khỏe tổng quát của trẻ, phát hiện sớm các bệnh lý như thiếu máu, nhiễm trùng, rối loạn chuyển hóa và các vấn đề tim mạch. Kết quả xét nghiệm máu cung cấp thông tin quan trọng để bác sĩ đưa ra các chẩn đoán chính xác và lập kế hoạch điều trị phù hợp cho trẻ.'),
(4, N'Chụp X-quang tim trẻ em', 300000, N'Chụp X-quang tim trẻ em là phương pháp sử dụng tia X để tạo ra hình ảnh chi tiết của tim và phổi trẻ em. Kỹ thuật này giúp bác sĩ phát hiện các bất thường về cấu trúc tim, phổi và các mạch máu lớn. Chụp X-quang tim thường được sử dụng để chẩn đoán các dị tật bẩm sinh, viêm phổi, và các vấn đề liên quan đến tim mạch. Quá trình chụp nhanh chóng và không đau, cung cấp thông tin hình ảnh cần thiết để hỗ trợ chẩn đoán và điều trị.'),
(5, N'Điều trị ICU', 5000000, N'Điều trị ICU (Intensive Care Unit) là dịch vụ chăm sóc đặc biệt cho các bệnh nhân nặng cần sự giám sát và hỗ trợ y tế liên tục. Các bệnh nhân ICU thường mắc các bệnh lý nghiêm trọng hoặc đã trải qua các ca phẫu thuật phức tạp. Phòng ICU được trang bị đầy đủ các thiết bị y tế hiện đại như máy thở, máy theo dõi huyết áp, và các thiết bị hỗ trợ sinh tồn khác. Điều trị ICU bao gồm việc theo dõi các dấu hiệu sinh tồn, quản lý đau, chăm sóc vết thương, và thực hiện các can thiệp y tế khẩn cấp khi cần thiết.'),
(5, N'Hồi sức tim phổi', 2000000, N'Hồi sức tim phổi (CPR) là một phương pháp cấp cứu quan trọng được sử dụng để duy trì lưu thông máu và hô hấp cho bệnh nhân ngừng tim đột ngột. Quá trình hồi sức tim phổi bao gồm các kỹ thuật như ép ngực và thổi ngạt để duy trì dòng máu và oxy đến các cơ quan quan trọng. Kỹ thuật này có thể kết hợp với việc sử dụng máy khử rung tim (AED) để khôi phục nhịp tim bình thường. Hồi sức tim phổi cần được thực hiện nhanh chóng và chính xác để tăng cơ hội sống sót và giảm thiểu tổn thương não cho bệnh nhân.'),
(5, N'Thở máy trong ICU', 2500000, N'Thở máy trong ICU là quá trình sử dụng máy thở để hỗ trợ hoặc thay thế chức năng hô hấp cho bệnh nhân nặng đang điều trị trong phòng ICU. Máy thở sẽ cung cấp không khí hoặc hỗn hợp khí giàu oxy vào phổi của bệnh nhân thông qua ống nội khí quản hoặc mặt nạ. Quá trình này giúp duy trì mức oxy và carbon dioxide ổn định trong máu, đảm bảo các cơ quan trong cơ thể hoạt động bình thường. Thở máy yêu cầu giám sát liên tục và điều chỉnh các thông số kỹ thuật phù hợp với tình trạng của bệnh nhân.'),
(5, N'Chăm sóc bệnh nhân sau phẫu thuật', 3000000, N'Chăm sóc bệnh nhân sau phẫu thuật là một dịch vụ quan trọng nhằm đảm bảo quá trình hồi phục an toàn và hiệu quả cho bệnh nhân sau khi trải qua các ca phẫu thuật phức tạp, đặc biệt là phẫu thuật tim. Quá trình này bao gồm việc theo dõi các dấu hiệu sinh tồn, quản lý đau, chăm sóc vết thương, và hỗ trợ bệnh nhân trong các hoạt động hàng ngày. Bác sĩ và điều dưỡng sẽ đánh giá tình trạng sức khỏe của bệnh nhân thường xuyên, điều chỉnh các biện pháp điều trị và cung cấp các hướng dẫn cần thiết để bệnh nhân hồi phục nhanh chóng.'),
(5, N'Thực hiện các can thiệp y tế khẩn cấp', 3500000, N'Thực hiện các can thiệp y tế khẩn cấp trong ICU là dịch vụ cung cấp các biện pháp y tế ngay lập tức để cứu sống và ổn định tình trạng bệnh nhân trong các tình huống nguy kịch. Các can thiệp này bao gồm hồi sức tim phổi, đặt ống nội khí quản, dùng thuốc cấp cứu, và các thủ thuật xâm lấn khác. Đội ngũ y tế trong ICU được đào tạo chuyên sâu và có kỹ năng cao để xử lý các tình huống khẩn cấp, đảm bảo bệnh nhân nhận được sự chăm sóc tốt nhất và cơ hội sống sót cao nhất.');


-- Insert sample data into LichDat table
INSERT INTO LichDat (IDCa, IDBenhNhan, IDBacSi, IDDichVu, ThuDatLich, NgayDatLich, TrangThai, TinhTrangThanhToan) VALUES
(1, 'BN000001', 'BS000001', 1, 2, '2023-06-20', 1, 0),
(2, 'BN000002', 'BS000002', 3, 3, '2023-06-21', 1, 1);
